#name, main, version and api are required
name: PHP_Server
main: cn.yuchuxi.php.PHP_Server
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0.0"
api: [ "1.0.14" ]
#load: POSTWORLD
load: STARTUP
author: yuchuxi.cn
# Authors and author will be added together in one list.
#authors: ["Example", "Another"]
description: PHP服务器插件
website: https://github.com/yuxibenxi/PHP_Server
# These dependencies are required for the plugin to start.
#depend: ["OtherPlugin", "ThisPlugin"]
# These dependencies are not required.
#softdepend: ["PluginA", "PluginB"]
# Log prefix in console
#prefix: "Example"
# Plugin will be loaded before these. Any cyclic loadbefore's or dependencies's will throw errors!
#loadbefore: ["ImportantPlugin"]